In [1]:
import numpy as np
from astropy.io import fits

In [92]:
d = fits.open('/Users/rliu/Downloads/test/mergePatchSrc/merged1.fits')

In [93]:
data = d[1].data
cols = d[1].columns
header_table = d[1].header

In [94]:
cols

ColDefs(
    name = 'flags'; format = '163X'
    name = 'id'; format = '1K'
    name = 'coord_ra'; format = '1D'; unit = 'rad'
    name = 'coord_dec'; format = '1D'; unit = 'rad'
    name = 'parent'; format = '1K'
    name = 'deblend_nChild'; format = '1J'
    name = 'deblend_psfCenter_x'; format = '1D'; unit = 'pixel'
    name = 'deblend_psfCenter_y'; format = '1D'; unit = 'pixel'
    name = 'deblend_psf_instFlux'; format = '1D'; unit = 'count'
    name = 'base_NaiveCentroid_x'; format = '1D'; unit = 'pixel'
    name = 'base_NaiveCentroid_y'; format = '1D'; unit = 'pixel'
    name = 'base_SdssCentroid_x'; format = '1D'; unit = 'pixel'
    name = 'base_SdssCentroid_y'; format = '1D'; unit = 'pixel'
    name = 'base_SdssCentroid_xErr'; format = '1E'; unit = 'pixel'
    name = 'base_SdssCentroid_yErr'; format = '1E'; unit = 'pixel'
    name = 'base_Blendedness_old'; format = '1D'
    name = 'base_Blendedness_raw'; format = '1D'
    name = 'base_Blendedness_raw_child_instFlux'; format = '

In [98]:
newcols = cols.names
# newcols.remove('flags')
newcols

['flags',
 'id',
 'coord_ra',
 'coord_dec',
 'parent',
 'deblend_nChild',
 'deblend_psfCenter_x',
 'deblend_psfCenter_y',
 'deblend_psf_instFlux',
 'base_NaiveCentroid_x',
 'base_NaiveCentroid_y',
 'base_SdssCentroid_x',
 'base_SdssCentroid_y',
 'base_SdssCentroid_xErr',
 'base_SdssCentroid_yErr',
 'base_Blendedness_old',
 'base_Blendedness_raw',
 'base_Blendedness_raw_child_instFlux',
 'base_Blendedness_raw_parent_instFlux',
 'base_Blendedness_abs',
 'base_Blendedness_abs_child_instFlux',
 'base_Blendedness_abs_parent_instFlux',
 'base_Blendedness_raw_child_xx',
 'base_Blendedness_raw_child_yy',
 'base_Blendedness_raw_child_xy',
 'base_Blendedness_raw_parent_xx',
 'base_Blendedness_raw_parent_yy',
 'base_Blendedness_raw_parent_xy',
 'base_Blendedness_abs_child_xx',
 'base_Blendedness_abs_child_yy',
 'base_Blendedness_abs_child_xy',
 'base_Blendedness_abs_parent_xx',
 'base_Blendedness_abs_parent_yy',
 'base_Blendedness_abs_parent_xy',
 'base_InputCount_value',
 'base_SdssShape_xx',
 '

In [99]:
vecs = data.field('id')[np.newaxis].T

In [100]:
for i in newcols[2:]:
    v=data.field(i)[np.newaxis].T
    vecs = np.hstack((vecs, v))

In [101]:
vecs

array([[ 1.09964586e+12,  5.80448266e+00, -2.19241018e-01, ...,
                    nan,  8.80000000e+01,  1.95430000e+04],
       [ 1.09964585e+12,  5.80448266e+00, -2.19224874e-01, ...,
                    nan,  1.31000000e+02,  1.67100000e+03],
       [ 1.09964585e+12,  5.80448273e+00, -2.17234293e-01, ...,
                    nan,  1.71000000e+02,  5.50300000e+03],
       ...,
       [ 1.09964585e+12,  5.81141126e+00, -2.17005111e-01, ...,
                    nan,  2.90000000e+01,  6.04700000e+03],
       [ 1.09964585e+12,  5.81141137e+00, -2.17080988e-01, ...,
                    nan,  1.25000000e+02,  5.87700000e+03],
       [ 1.09964585e+12,  5.81141457e+00, -2.19229756e-01, ...,
                    nan,  1.24000000e+02,  1.62500000e+03]])

In [102]:
print('\n'.join(' '.join(str(x) for x in row) for row in vecs))

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [77]:
v1 = data.field('id')[np.newaxis].T
v2 = data.field('coord_ra')[np.newaxis].T
v3 = data.field('coord_dec')[np.newaxis].T

In [78]:
v12 = np.hstack((v1,v2))

In [80]:
np.hstack((v12, v3))

array([[ 1.09964586e+12,  5.80448266e+00, -2.19241018e-01],
       [ 1.09964585e+12,  5.80448266e+00, -2.19224874e-01],
       [ 1.09964585e+12,  5.80448273e+00, -2.17234293e-01],
       ...,
       [ 1.09964585e+12,  5.81141126e+00, -2.17005111e-01],
       [ 1.09964585e+12,  5.81141137e+00, -2.17080988e-01],
       [ 1.09964585e+12,  5.81141457e+00, -2.19229756e-01]])

In [71]:
a = np.array([1,2,3])[np.newaxis]
b = np.array([2,3,4])[np.newaxis]
np.hstack((a.T,b.T))

array([[1, 2],
       [2, 3],
       [3, 4]])